Matrizes

In [6]:
import numpy as np

In [7]:
matriz = np.array([[2, 3, 1], [4, 5, 7]])

In [8]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [9]:
matriz.shape

(2, 3)

In [10]:
matriz[0]

array([2, 3, 1])

In [11]:
matriz[1]

array([4, 5, 7])

In [15]:
matriz[1][0]

4

In [18]:
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
        print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
